import type { Metadata } from "next"
import '../../envConfig'
import "./globals.css"

export const metadata: Metadata = {
  title: "GitConnect",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  )
}
